import Head from 'next/head';
import HomeContent from '../_src/components/home/HomeContent';
import Wrapper from '../_src/components/_common/Wrapper';

function Home() {
  return (
    <div>
      <Head>
        <title>Uraa-Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <HomeContent />
      </Wrapper>
    </div>
  );
}

export default Home;
